# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "uwbbi/bionic-arm64"

  config.vm.provision "shell", inline: "mkdir ~/data"
  config.vm.provision :file, source: './data', destination: '~/data'
  config.vm.provision "shell", path: "./data/setup.sh", privileged: false
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
  #sudo apt-get update
  #yes y | sudo apt-get upgrade
  SHELL
end
