datadog:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  site: datadoghq.com
  tags:

    - env:macbook
  # Disable kubelet TLS Verification in minikube
  kubelet:
    tlsVerify: false

  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true

  orchestratorExplorer:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    socketEnabled: false
    portEnabled: true
  processAgent:
    enabled: true
    processCollection: true

  clusterChecks:
    enabled: true

  podAnnotations: 
      ad.datadoghq.com/eg-datadog-java-test.checks: |
        {    
          "kafka": {    
            "init_config": {    
              "is_jmx": "true",
              "collect_default_metrics": "true"
            },   
            "instances": [
              {    
                "host": "%%host%%",
                "port": "9091"
              }    
            ]    
          }    
        } 

  # These 3 integrations error by default in minikube
  ignoreAutoConfig:
    - etcd
    - kube_controller_manager 
    - kube_scheduler 

clusterAgent:
  enabled: true