datadog:
  # Disable kubelet TLS Verification in minikube
  kubelet:
    tlsVerify: false

  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true

  orchestratorExplorer:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    socketEnabled: false
    portEnabled: true
  processAgent:
    enabled: true
    processCollection: true

  clusterChecks:
    enabled: true

  # These 3 integrations error by default in minikube
  ignoreAutoConfig:
    - etcd
    - kube_controller_manager 
    - kube_scheduler 

clusterAgent:
  enabled: true
